### ISSUE TITLE
Plugin can't be instantiated (DelugeV2)

### ISSUE THREAD

**Issue by ben-ba** [bendikro/deluge-iface-watch#2]
Is this still a problem in v2 for Deluge v2?
I would expect this to be resolved due to [Remove no-op Linux kernel 2.x parser](https://github.com/ftao/python-ifcfg/commit/9b96c9d410fb4ef4c5cc6eb90e33fc40c8bbc7ba#diff-1ebc4a348c4604a09497d268049134bb) fix in python-ifcfg

_Originally posted by @bendikro in https://github.com/bendikro/deluge-iface-watch/issues/1#issuecomment-551627023_

> 2020-11-09 11:18:01 [ERROR   ][deluge.pluginmanagerbase         :154 ] Unable to instantiate plugin 'IfaceWatch' from '/config/plugins/IfaceWatch-2.0-py3.6.egg'!
2020-11-09 11:18:01 [ERROR   ][deluge.pluginmanagerbase         :1343] No module named 'ifcfg'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/deluge/pluginmanagerbase.py", line 148, in enable_plugin
    instance = cls(plugin_name.replace('-', '_'))
  File "/config/plugins/IfaceWatch-2.0-py3.6.egg/ifacewatch/__init__.py", line 38, in __init__
    from .core import Core as CorePluginClass
  File "/config/plugins/IfaceWatch-2.0-py3.6.egg/ifacewatch/core.py", line 20, in <module>
    import ifcfg
ModuleNotFoundError: No module named 'ifcfg'
2020-11-09 11:18:05 [ERROR   ][deluge.pluginmanagerbase         :154 ] Unable to instantiate plugin 'IfaceWatch' from '/config/plugins/IfaceWatch-2.0-py3.6.egg'!
2020-11-09 11:18:05 [ERROR   ][deluge.pluginmanagerbase         :1343] No module named 'ifcfg'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/deluge/pluginmanagerbase.py", line 148, in enable_plugin
    instance = cls(plugin_name.replace('-', '_'))
  File "/config/plugins/IfaceWatch-2.0-py3.6.egg/ifacewatch/__init__.py", line 38, in __init__
    from .core import Core as CorePluginClass
  File "/config/plugins/IfaceWatch-2.0-py3.6.egg/ifacewatch/core.py", line 20, in <module>
    import ifcfg
ModuleNotFoundError: No module named 'ifcfg'

**Comment by ben-ba** [comment]
In the egg-file, the modules ifcfg and pyiface are missing.
I successfully add them, by adding blank `__init__.py` files in all directories in the directory "include".
Plugin load successfully, but no GUI on the unofficial macOS deluge2.app.

> 020-11-09 15:35:04 [INFO    ][deluge.plugin.ifacewatch.util.logger     :39  ] IfaceWatch.core:47: IP was changed from outside IfaceWatch: None -> 0.0.0.0
2020-11-09 15:35:04 [INFO    ][deluge.plugin.ifacewatch.util.logger     :39  ] IfaceWatch.core:62: Enabled Iface Watch 2.0
2020-11-09 15:35:04 [INFO    ][deluge.plugin.ifacewatch.util.logger     :39  ] IfaceWatch.core:80: Scheduling watch with interval 10.
2020-11-09 15:35:04 [INFO    ][deluge.pluginmanagerbase                 :189 ] Plugin IfaceWatch enabled...
